export const grid = [
  [
    { answer: "P" },
    { answer: "I" },
    { answer: "N" },
    { answer: "A" },
    null,
    { answer: "B" },
    { answer: "E" },
    { answer: "A" },
    { answer: "R" },
    { answer: "D" },
    null,
    { answer: "V" },
    { answer: "A" },
    { answer: "S" },
    { answer: "E" },
  ],
  [
    { answer: "B" },
    { answer: "R" },
    { answer: "O" },
    { answer: "S" },
    null,
    { answer: "C" },
    { answer: "A" },
    { answer: "M" },
    { answer: "E" },
    { answer: "O" },
    null,
    { answer: "I" },
    { answer: "N" },
    { answer: "C" },
    { answer: "A" },
  ],
  [
    { answer: "J" },
    { answer: "A" },
    { answer: "V" },
    { answer: "A" },
    { answer: "S" },
    { answer: "C" },
    { answer: "R" },
    { answer: "I" },
    { answer: "P" },
    { answer: "T" },
    null,
    { answer: "E" },
    { answer: "G" },
    { answer: "O" },
    { answer: "T" },
  ],
  [
    { answer: "S" },
    { answer: "N" },
    { answer: "O" },
    { answer: "R" },
    { answer: "E" },
    { answer: "S" },
    null,
    { answer: "G" },
    { answer: "E" },
    { answer: "E" },
    null,
    { answer: "T" },
    { answer: "U" },
    { answer: "N" },
    { answer: "A" },
  ],
  [
    null,
    null,
    { answer: "C" },
    { answer: "U" },
    { answer: "E" },
    null,
    { answer: "G" },
    { answer: "O" },
    { answer: "L" },
    { answer: "D" },
    { answer: "E" },
    { answer: "N" },
    { answer: "S" },
    { answer: "E" },
    { answer: "T" },
  ],
  [
    { answer: "S" },
    { answer: "C" },
    { answer: "A" },
    { answer: "L" },
    { answer: "P" },
    { answer: "E" },
    { answer: "R" },
    null,
    null,
    { answer: "U" },
    { answer: "M" },
    { answer: "A" },
    null,
    null,
    null,
  ],
  [
    { answer: "E" },
    { answer: "R" },
    { answer: "I" },
    { answer: "E" },
    null,
    { answer: "M" },
    { answer: "A" },
    { answer: "I" },
    { answer: "D" },
    null,
    { answer: "I" },
    { answer: "M" },
    { answer: "P" },
    { answer: "L" },
    { answer: "Y" },
  ],
  [
    { answer: "E" },
    { answer: "O" },
    { answer: "N" },
    null,
    { answer: "P" },
    { answer: "O" },
    { answer: "D" },
    { answer: "C" },
    { answer: "A" },
    { answer: "S" },
    { answer: "T" },
    null,
    { answer: "H" },
    { answer: "U" },
    { answer: "E" },
  ],
  [
    { answer: "S" },
    { answer: "W" },
    { answer: "E" },
    { answer: "D" },
    { answer: "E" },
    null,
    { answer: "S" },
    { answer: "U" },
    { answer: "V" },
    { answer: "S" },
    null,
    { answer: "P" },
    { answer: "O" },
    { answer: "R" },
    { answer: "N" },
  ],
  [
    null,
    null,
    null,
    { answer: "O" },
    { answer: "E" },
    { answer: "D" },
    null,
    null,
    { answer: "I" },
    { answer: "N" },
    { answer: "V" },
    { answer: "I" },
    { answer: "T" },
    { answer: "E" },
    { answer: "S" },
  ],
  [
    { answer: "G" },
    { answer: "I" },
    { answer: "V" },
    { answer: "E" },
    { answer: "P" },
    { answer: "R" },
    { answer: "O" },
    { answer: "P" },
    { answer: "S" },
    null,
    { answer: "E" },
    { answer: "C" },
    { answer: "O" },
    null,
    null,
  ],
  [
    { answer: "I" },
    { answer: "S" },
    { answer: "I" },
    { answer: "S" },
    null,
    { answer: "A" },
    { answer: "V" },
    { answer: "E" },
    null,
    { answer: "G" },
    { answer: "R" },
    { answer: "A" },
    { answer: "S" },
    { answer: "P" },
    { answer: "S" },
  ],
  [
    { answer: "M" },
    { answer: "A" },
    { answer: "R" },
    { answer: "K" },
    null,
    { answer: "P" },
    { answer: "U" },
    { answer: "T" },
    { answer: "O" },
    { answer: "N" },
    { answer: "A" },
    { answer: "S" },
    { answer: "H" },
    { answer: "O" },
    { answer: "W" },
  ],
  [
    { answer: "M" },
    { answer: "A" },
    { answer: "G" },
    { answer: "I" },
    null,
    { answer: "E" },
    { answer: "L" },
    { answer: "E" },
    { answer: "N" },
    { answer: "A" },
    null,
    { answer: "S" },
    { answer: "O" },
    { answer: "S" },
    { answer: "A" },
  ],
  [
    { answer: "E" },
    { answer: "C" },
    { answer: "O" },
    { answer: "N" },
    null,
    { answer: "R" },
    { answer: "E" },
    { answer: "S" },
    { answer: "E" },
    { answer: "W" },
    null,
    { answer: "O" },
    { answer: "P" },
    { answer: "E" },
    { answer: "N" },
  ],
];

export const exampleAcrosses = [
  { num: 1, clue: "___ colada" },
  { num: 5, clue: "Symbol of marriage for Amish men" },
  { num: 10, clue: "Container for a bouquet" },
  { num: 14, clue: "Super Smash ___" },
  { num: 15, clue: "Small role in a film" },
  { num: 16, clue: "Member of a New World empire" },
  { num: 17, clue: "Programming language since 1995" },
  { num: 19, clue: "Entertainment award quintet, for short" },
  { num: 20, clue: "Sleeps sound-ly?" },
  { num: 21, clue: "'Oh, gosh!'" },
  { num: 22, clue: "Fish in a salade nicoise" },
  { num: 23, clue: "Theater signal" },
  {
    num: 24,
    clue: "Rare tennis feat in which one plater wins 24 straight points",
  },
  { num: 26, clue: "One reselling tickets" },
  { num: 29, clue: "Actress Thurman" },
  { num: 30, clue: "Cleveland's lake" },
  { num: 31, clue: "One of eight 'a-milking' in a Christmas carol" },
  { num: 34, clue: "Hint at" },
  { num: 38, clue: "Seemingly endless time span" },
  { num: 39, clue: "Audio download" },
  { num: 41, clue: "Shade" },
  { num: 42, clue: "Finn's neighbor" },
  { num: 44, clue: "Highlanders and Foresters, e.g." },
  { num: 45, clue: "NSFW stuff" },
  { num: 46, clue: "Ref. that added 'turnt' and 'deepfake' in 2023" },
  { num: 48, clue: "Asks to come" },
  { num: 50, clue: "Offer kudos, in modern lingo" },
  { num: 55, clue: "Green prefix" },
  { num: 56, clue: "Egyptian mother goddess" },
  { num: 57, clue: "'___ Maria' (hymn)" },
  { num: 58, clue: "Gets a grip on, literally or figuratively" },
  { num: 61, clue: "Swindler's target" },
  {
    num: 62,
    clue: "Keep up appearances, say... or what to do with the ends of 17-, 24-, 39 and 50-Across?",
  },
  { num: 64, clue: "Three Wise Men" },
  { num: 65, clue: "Kagan on the Supreme Court" },
  { num: 66, clue: "Slugger Sammy" },
  { num: 67, clue: "Supply-and-demand subj." },
  { num: 68, clue: "Mend again, as a hem" },
  { num: 69, clue: "'Yes! We're ___'" },
];

export const exampleDowns = [
  { num: 1, clue: "Classic lunchbox sandwiches, for short" },
  { num: 2, clue: "Tehran's land" },
  { num: 3, clue: "Dentist's anesthetic" },
  { num: 4, clue: "In most cases" },
  { num: 5, clue: "Secretly loops in, as on an email" },
  { num: 6, clue: "Body part with a ring, or a ringing" },
  { num: 7, clue: "Pal, in Puerto Rico" },
  { num: 8, clue: "Drive away" },
  { num: 9, clue: "End of an academic URL" },
  { num: 10, clue: "Country whose cuisine includes pho and banh mi" },
  { num: 11, clue: "Scottish cattle breed" },
  { num: 12, clue: "British pastry served with tea" },
  { num: 13, clue: "Really bother" },
  { num: 18, clue: "Slowly drip (out)" },
  { num: 24, clue: "Alumni" },
  { num: 25, clue: "Give off, as light" },
  { num: 26, clue: "Observes" },
  { num: 27, clue: "Brag immodestly" },
  { num: 28, clue: "Moody rock subgenre" },
  { num: 32, clue: "Post-E.R. area" },
  { num: 33, clue: "Geena of 'Beetlejuice'" },
  { num: 35, clue: "Adobe image-editing software" },
  { num: 36, clue: "Attract, as a siren might" },
  { num: 37, clue: "Cravings" },
  { num: 39, clue: "Sound from a chick" },
  { num: 40, clue: "Govt.-issued ID" },
  { num: 43, clue: "Soft leather variety" },
  { num: 45, clue: "Painter with a noted 'blue period'" },
  { num: 47, clue: "Don ___, 'Mad Men' adman" },
  { num: 49, clue: "Aloe ___" },
  { num: 50, clue: "Easy crossword clue, e.g." },
  { num: 51, clue: "Physicist Newton" },
  { num: 52, clue: "Late August baby, astrologically" },
  { num: 53, clue: "Tiny egg cell" },
  { num: 54, clue: "'For ___ sake!'" },
  { num: 58, clue: "Work on some jerky, say" },
  { num: 59, clue: "Prepare for a selfie" },
  { num: 60, clue: "one of seve 'a-swimming' in a Christmas carol" },
  { num: 63, clue: "Dollar bill" },
];
